// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace GPGSIds
{
public static class RollingAnimal
{
        public const string leaderboard_stage_1_rank_normal = "CgkI4bHZyOoaEAIQCw"; // <GPGSID>
        public const string achievement_stage_5_clear = "CgkI4bHZyOoaEAIQBQ"; // <GPGSID>
        public const string leaderboard_stage_6_rank_easy = "CgkI4bHZyOoaEAIQGQ"; // <GPGSID>
        public const string achievement_stage_3_clear = "CgkI4bHZyOoaEAIQAw"; // <GPGSID>
        public const string leaderboard_stage_3_rank_easy = "CgkI4bHZyOoaEAIQEA"; // <GPGSID>
        public const string leaderboard_stage_4_rank_easy = "CgkI4bHZyOoaEAIQEw"; // <GPGSID>
        public const string achievement_stage1_clear = "CgkI4bHZyOoaEAIQAQ"; // <GPGSID>
        public const string achievement_stage_4_clear = "CgkI4bHZyOoaEAIQBA"; // <GPGSID>
        public const string leaderboard_stage_3_rank_normal = "CgkI4bHZyOoaEAIQEg"; // <GPGSID>
        public const string leaderboard_stage_1_rank_hard = "CgkI4bHZyOoaEAIQDA"; // <GPGSID>
        public const string achievement_stage_6_clear = "CgkI4bHZyOoaEAIQBg"; // <GPGSID>
        public const string leaderboard_stage_2_rank_normal = "CgkI4bHZyOoaEAIQDg"; // <GPGSID>
        public const string leaderboard_stage_4_rank_normal = "CgkI4bHZyOoaEAIQFA"; // <GPGSID>
        public const string leaderboard_stage_1_rank_easy = "CgkI4bHZyOoaEAIQBw"; // <GPGSID>
        public const string leaderboard_stage_6_rank_hard = "CgkI4bHZyOoaEAIQGw"; // <GPGSID>
        public const string leaderboard_stage_2_rank_easy = "CgkI4bHZyOoaEAIQDQ"; // <GPGSID>
        public const string leaderboard_stage_2_rank_hard = "CgkI4bHZyOoaEAIQDw"; // <GPGSID>
        public const string leaderboard_stage_5_rank_hard = "CgkI4bHZyOoaEAIQGA"; // <GPGSID>
        public const string leaderboard_stage_6_rank_normal = "CgkI4bHZyOoaEAIQGg"; // <GPGSID>
        public const string leaderboard_stage_3_rank_hard = "CgkI4bHZyOoaEAIQEQ"; // <GPGSID>
        public const string achievement_stage2_clear = "CgkI4bHZyOoaEAIQAg"; // <GPGSID>
        public const string leaderboard_stage_5_rank_normal = "CgkI4bHZyOoaEAIQFw"; // <GPGSID>
        public const string leaderboard_stage_5_rank_easy = "CgkI4bHZyOoaEAIQFg"; // <GPGSID>
        public const string leaderboard_stage_4_rank_hard = "CgkI4bHZyOoaEAIQFQ"; // <GPGSID>

}
}
